/* Catálogo del documento informativo del Real Decreto 723/2026 (art. 3.2, letras a–q).
   Solo datos: pasos del asistente, campos del formulario y los 17 apartados legales.
   Lo usan el formulario (sección 03), las validaciones y el modelo del documento (sección 02),
   la vista previa y el PDF (sección 04). Textos redactados a partir del BOE-A-2026-19200.
   En el navegador: window.__IC_CATALOG__. En Node: require(). */
(function (root) {
  "use strict";

  var esTemporal = function (d) { return d.tipoContrato === "temporal"; };
  var noHogar = function (d) { return !d.modoHogar; };

  // --- Textos por defecto (editables por el usuario). Cuando el art. 3.3 lo permite,
  //     remiten a la ley o al convenio con una referencia precisa. ---
  var TEXTOS = {
    pruebaCondiciones: "La empresa y la persona trabajadora están obligadas a realizar las experiencias que constituyen el objeto de la prueba. Durante el periodo de prueba, cualquiera de las partes puede resolver la relación laboral (art. 14 del Estatuto de los Trabajadores).",
    modificacionJornada: "La duración y la distribución de la jornada, y en su caso los turnos, solo podrán modificarse en los supuestos y con los procedimientos previstos en el convenio colectivo y en el Estatuto de los Trabajadores: distribución irregular de la jornada (art. 34.2) y modificación sustancial de condiciones de trabajo (art. 41).",
    horasExtra: "La realización de horas extraordinarias es voluntaria, salvo pacto en convenio o contrato, con un máximo de 80 al año. Se retribuyen en la cuantía que fije el convenio, nunca inferior al valor de la hora ordinaria, o se compensan con descanso retribuido; sin pacto, se compensan con descanso en los cuatro meses siguientes (art. 35 del Estatuto de los Trabajadores).",
    horasExtraParcial: "Al tratarse de un contrato a tiempo parcial, no se pueden realizar horas extraordinarias, salvo las necesarias para prevenir o reparar siniestros y otros daños extraordinarios y urgentes (arts. 12.4.c y 35.3 del Estatuto de los Trabajadores). Las horas complementarias, si se pactan, se regirán por el art. 12.5 del Estatuto de los Trabajadores.",
    vacacionesProcedimiento: "El periodo o periodos de disfrute se fijan de común acuerdo entre la empresa y la persona trabajadora, de conformidad con lo previsto en el convenio colectivo. La persona trabajadora conocerá las fechas que le correspondan al menos dos meses antes del comienzo del disfrute (art. 38 del Estatuto de los Trabajadores).",
    preavisoIrregular: "5 días de antelación como mínimo (art. 34.2 del Estatuto de los Trabajadores), salvo que el convenio fije otro plazo.",
    formacion: "La persona trabajadora tiene derecho a la formación necesaria para adaptarse a las modificaciones de su puesto, a cargo de la empresa y considerada tiempo de trabajo efectivo; a un permiso retribuido de 20 horas anuales de formación profesional para el empleo cuando tenga al menos un año de antigüedad (art. 23 del Estatuto de los Trabajadores); a la formación en prevención de riesgos laborales (art. 19 de la Ley 31/1995), y a la que establezca el convenio colectivo.",
    algoritmosNo: "La empresa no utiliza sistemas algorítmicos o automatizados de toma de decisiones que afecten a las condiciones de trabajo.",
    planIgualdadNo: "La empresa no dispone de plan de igualdad.",
    conciliacionNo: "La empresa no dispone de una política de conciliación propia distinta de la prevista en la legislación laboral y en el convenio colectivo.",
    acosoNo: "La empresa no dispone todavía de protocolo frente al acoso sexual y por razón de sexo.",
    lgtbiNo: "La empresa no dispone de un conjunto planificado de medidas y recursos para la igualdad y no discriminación de las personas LGTBI.",
    extincion: "El contrato se extinguirá por las causas y con los requisitos formales previstos en el artículo 49 y siguientes del Estatuto de los Trabajadores. El despido se comunica por escrito, indicando los hechos que lo motivan y la fecha de efectos (arts. 53 y 55); en el despido por causas objetivas, la empresa debe dar un preaviso de 15 días. En caso de dimisión, la persona trabajadora debe dar el preaviso que fije el convenio colectivo o, en su defecto, la costumbre del lugar. En los contratos temporales de más de un año, la parte que denuncie el contrato debe notificarlo con al menos 15 días de antelación (art. 49.1.c).",
    ssEntidad: "Instituto Nacional de la Seguridad Social (INSS)",
    mejorasNo: "No existen mejoras voluntarias de la acción protectora de la Seguridad Social ni planes o fondos de pensiones promovidos en favor de la persona trabajadora.",
    modificaciones: "Las condiciones de los apartados d), e), f) y g) solo podrán modificarse en los supuestos y con los procedimientos previstos en el Estatuto de los Trabajadores (movilidad funcional, art. 39; modificación sustancial de condiciones de trabajo, art. 41; distribución irregular de la jornada, art. 34.2) y en el convenio colectivo. Cualquier cambio se comunicará por escrito lo antes posible y, como tarde, el día en que surta efecto (arts. 5 y 7.3 del Real Decreto 723/2026).",
    ettNo: "La persona trabajadora no ha sido cedida por una empresa de trabajo temporal.",
    // Modo «familia empleadora»: relación laboral especial del servicio del hogar familiar. Textos redactados a partir
    // del RD 1620/2011 consolidado (BOE-A-2011-17975, con el RDL 16/2022) y del RD 893/2024 (BOE-A-2024-18182).
    hogarAviso: "El empleo en el hogar familiar es una relación laboral especial: se rige por el Real Decreto 1620/2011 y el RD 723/2026 se aplica en los términos que esta prevé. Los apartados están adaptados a este caso; revísalos antes de entregar el documento.",
    hogarConvenio: "No existe convenio colectivo aplicable a la relación laboral especial del servicio del hogar familiar, que se rige por el Real Decreto 1620/2011 y, en lo que resulte compatible, por el Estatuto de los Trabajadores.",
    hogarPrueba: "La persona empleadora y la persona trabajadora están obligadas a cumplir sus respectivas prestaciones. Durante el periodo de prueba, cualquiera de las partes puede resolver la relación laboral con el preaviso que se pacte, que no puede superar siete días naturales (art. 6.2 del Real Decreto 1620/2011).",
    hogarModificacionJornada: "El horario se fija por acuerdo entre las partes (art. 9.1 del Real Decreto 1620/2011). Los cambios de jornada u horario se acordarán entre ambas partes o, en su defecto, se regirán por el Estatuto de los Trabajadores en lo que resulte compatible con esta relación especial (art. 3 del Real Decreto 1620/2011).",
    hogarHorasExtra: "Las horas extraordinarias se rigen por el art. 35 del Estatuto de los Trabajadores (art. 9.3 del Real Decreto 1620/2011): son voluntarias salvo pacto, con un máximo de 80 al año, y se retribuyen en la cuantía que se acuerde, nunca inferior al valor de la hora ordinaria, o se compensan con descanso retribuido; sin pacto, se compensan con descanso en los cuatro meses siguientes.",
    hogarVacaciones: "Pueden dividirse en varios periodos, uno de ellos de al menos 15 días naturales seguidos. Las fechas se acuerdan entre las partes; a falta de acuerdo, la persona empleadora puede fijar 15 días según las necesidades familiares y la persona trabajadora elige libremente el resto. Las fechas se conocerán con dos meses de antelación (art. 9.7 del Real Decreto 1620/2011).",
    hogarFormacion: "La persona trabajadora tiene derecho a recibir, al ser contratada, formación en prevención de riesgos laborales centrada en las tareas del hogar, a través de la plataforma pública gestionada por Fundae, dentro de la jornada siempre que sea posible o compensada con descanso equivalente. Si alguna tarea entraña riesgos excepcionales, la persona empleadora proporcionará a su cargo una formación complementaria (art. 5.3 y disposición adicional quinta del Real Decreto 893/2024). Además, tiene los derechos de formación del art. 23 del Estatuto de los Trabajadores en lo que resulten compatibles con esta relación especial.",
    hogarExtincion: "El contrato puede extinguirse por las causas del art. 49.1 del Estatuto de los Trabajadores. Además, la persona empleadora puede extinguirlo, de forma justificada, por disminución de los ingresos o aumento de los gastos de la familia por una circunstancia sobrevenida, por un cambio sustancial de las necesidades familiares o por un comportamiento de la persona trabajadora que justifique razonablemente la pérdida de confianza. En esos casos debe comunicarlo por escrito indicando la causa, poner a la vez a su disposición una indemnización de 12 días de salario por año de servicio, con un máximo de seis mensualidades, y dar un preaviso de 20 días si la relación ha durado más de un año, o de 7 días en los demás casos, que puede sustituir por los salarios de ese periodo (art. 11 del Real Decreto 1620/2011). En caso de dimisión, la persona trabajadora debe dar el preaviso que marque la costumbre del lugar (art. 49.1.d del Estatuto de los Trabajadores).",
    hogarModificaciones: "Las condiciones de los apartados d), e), f) y g) se modificarán por acuerdo entre las partes o, en su defecto, según lo previsto en el Estatuto de los Trabajadores en lo que resulte compatible con esta relación especial (art. 3 del Real Decreto 1620/2011). Cualquier cambio se comunicará por escrito lo antes posible y, como tarde, el día en que surta efecto (arts. 5 y 7.3 del Real Decreto 723/2026).",
    hogarIgualdad: "Al tratarse de empleo en el hogar familiar y no de una empresa, no existe plan de igualdad ni política de conciliación propia. La persona trabajadora tiene derecho a la protección frente a la violencia y el acoso (disposición adicional segunda del Real Decreto 893/2024); el protocolo de actuación para el servicio del hogar familiar lo publica el Instituto Nacional de Seguridad y Salud en el Trabajo.",
    hogarLgtbi: "Al tratarse de empleo en el hogar familiar y no de una empresa, no existe un conjunto planificado de medidas para la igualdad de las personas LGTBI.",
    hogarAlgoritmos: "La persona empleadora no utiliza sistemas algorítmicos o automatizados de toma de decisiones."
  };

  var PASOS = [
    { n: 1, id: "empresa", titulo: "Empresa" },
    { n: 2, id: "contrato", titulo: "Trabajador y contrato" },
    { n: 3, id: "salario", titulo: "Salario" },
    { n: 4, id: "jornada", titulo: "Jornada y vacaciones" },
    { n: 5, id: "resto", titulo: "Resto de condiciones" },
    { n: 6, id: "revisar", titulo: "Revisar y descargar" }
  ];

  // Campos. ambito: "empresa" se guarda con la empresa para el siguiente contrato;
  // "trabajador" es propio de cada documento. requerido/visible: booleano o función(datos).
  // labelHogar/ayudaHogar/defectoHogar: lo que cambia en el modo familia empleadora.
  // grupo: subtítulo dentro del paso 5, que es largo.
  var CAMPOS = [
    // ---------- Paso 1: Empresa (apartados a y c) ----------
    { id: "modoHogar", paso: 1, ambito: "empresa", tipo: "checkbox", defecto: false,
      label: "Soy una familia que contrata a una persona para el hogar",
      ayuda: "Actívalo si contratas para el servicio del hogar familiar (limpieza, cuidados, etc.)." },
    { id: "empresaNombre", paso: 1, ambito: "empresa", tipo: "text", requerido: true, max: 160, apartado: "a",
      label: "Nombre o razón social de la empresa", labelHogar: "Tu nombre y apellidos",
      ayuda: "Tal como figura en tu alta en la Seguridad Social.", ejemplo: "Ej.: Bar La Esquina, S.L.", autocomplete: "organization" },
    { id: "empresaNif", paso: 1, ambito: "empresa", tipo: "text", max: 12, apartado: "a",
      label: "NIF (opcional)", ayuda: "El de la empresa; si eres autónomo o una familia, tu NIF. Si lo prefieres, déjalo en blanco y escríbelo a mano en el papel.", ejemplo: "Ej.: B12345678" },
    { id: "empresaDomicilio", paso: 1, ambito: "empresa", tipo: "text", requerido: true, max: 200, apartado: "c",
      label: "Domicilio social", labelHogar: "Tu domicilio",
      ayuda: "Calle, número, código postal y localidad.", ejemplo: "Ej.: C/ Mayor 12, 28013 Madrid", autocomplete: "street-address" },
    { id: "centroIgualDomicilio", paso: 1, ambito: "trabajador", tipo: "checkbox", defecto: true, apartado: "c",
      label: "Trabajará en el mismo domicilio" },
    { id: "centroTrabajo", paso: 1, ambito: "trabajador", tipo: "text", max: 200, apartado: "c",
      visible: function (d) { return !d.centroIgualDomicilio; }, requerido: function (d) { return !d.centroIgualDomicilio; },
      label: "Centro de trabajo habitual", ayuda: "Dirección donde trabajará normalmente.", ejemplo: "Ej.: Local de C/ Luna 3, 28004 Madrid" },
    { id: "lugarNotas", paso: 1, ambito: "trabajador", tipo: "textarea", max: 600, apartado: "c",
      label: "Otras circunstancias del lugar de trabajo (opcional)",
      ayuda: "Si teletrabaja (indica el centro al que queda adscrita), trabaja en varios centros o en lugares móviles, o elige libremente dónde trabajar.",
      ejemplo: "Ej.: Teletrabajo dos días a la semana; adscrita al centro de C/ Luna 3." },
    { id: "provincia", paso: 1, ambito: "empresa", tipo: "select", visible: noHogar, requerido: noHogar, opciones: "provincias",
      label: "Provincia del centro de trabajo", ayuda: "Te ayuda a encontrar tu convenio colectivo." },
    { id: "numTrabajadores", paso: 1, ambito: "empresa", tipo: "number", visible: noHogar, requerido: noHogar, min: 1, max: 100000, incremento: 1,
      label: "Número de personas en plantilla", labelHogar: "Número de personas que tienes contratadas",
      ayuda: "Sirve para saber qué obligaciones te afectan: plan de igualdad, medidas LGTBI y duración del periodo de prueba.", ejemplo: "Ej.: 4" },

    // ---------- Paso 2: Trabajador y contrato (apartados a, b, d, e y h) ----------
    { id: "trabajadorNombre", paso: 2, ambito: "trabajador", tipo: "text", requerido: true, max: 160, apartado: "a",
      label: "Nombre y apellidos de la persona trabajadora", ayuda: "Tal como aparece en su DNI o NIE.", ejemplo: "Ej.: Lucía Martín Pérez" },
    { id: "trabajadorDni", paso: 2, ambito: "trabajador", tipo: "text", max: 12, apartado: "a",
      label: "DNI o NIE (opcional)", ayuda: "Si lo prefieres, déjalo en blanco y escríbelo a mano en el papel.", ejemplo: "Ej.: 12345678Z" },
    { id: "fechaInicio", paso: 2, ambito: "trabajador", tipo: "date", requerido: true, apartado: "b",
      label: "Fecha de inicio", ayuda: "Día en que empieza a trabajar. El documento debe entregarse antes." },
    { id: "tipoContrato", paso: 2, ambito: "trabajador", tipo: "select", requerido: true, defecto: "indefinido", apartado: "b",
      opciones: [{ valor: "indefinido", texto: "Indefinido" }, { valor: "temporal", texto: "Temporal" }, { valor: "fijo-discontinuo", texto: "Fijo discontinuo" }],
      label: "Tipo de contrato" },
    { id: "fechaFin", paso: 2, ambito: "trabajador", tipo: "date", apartado: "b",
      visible: esTemporal, requerido: function (d) { return esTemporal(d) && !d.duracionPrevista; },
      label: "Fecha de finalización", ayuda: "Si no se conoce la fecha exacta, rellena la duración previsible." },
    { id: "duracionPrevista", paso: 2, ambito: "trabajador", tipo: "text", max: 200, apartado: "b",
      visible: esTemporal, requerido: function (d) { return esTemporal(d) && !d.fechaFin; },
      label: "Duración previsible", ejemplo: "Ej.: Hasta la reincorporación de la persona sustituida" },
    { id: "causaTemporal", paso: 2, ambito: "trabajador", tipo: "textarea", max: 1500, apartado: "d",
      visible: esTemporal, requerido: esTemporal,
      label: "Causa del contrato temporal",
      ayuda: "La causa legal (circunstancias de la producción o sustitución de una persona), los hechos concretos que la justifican y su relación con la duración del contrato (art. 15 del Estatuto de los Trabajadores).",
      ejemplo: "Ej.: Aumento de clientela en la temporada de verano, del 1 de junio al 30 de septiembre; se necesita reforzar la barra durante ese periodo." },
    { id: "puesto", paso: 2, ambito: "trabajador", tipo: "text", requerido: true, max: 120, apartado: "e",
      label: "Puesto de trabajo", ejemplo: "Ej.: Camarero/a de barra" },
    { id: "funciones", paso: 2, ambito: "trabajador", tipo: "textarea", requerido: true, max: 1500, apartado: "d",
      label: "Funciones principales", ayuda: "Lo que hará en su trabajo, con suficiente detalle para entender el contenido del puesto.",
      ejemplo: "Ej.: Atención a clientes en barra y sala, preparación de bebidas y cafés, cobro y limpieza de la zona de trabajo." },
    { id: "categoria", paso: 2, ambito: "trabajador", tipo: "text", max: 160, apartado: "e",
      requerido: noHogar, defectoHogar: "Empleado/a de hogar",
      label: "Grupo o categoría profesional", ayuda: "La que marca tu convenio colectivo para este puesto.", ayudaHogar: "En el empleo de hogar suele bastar con «Empleado/a de hogar».", ejemplo: "Ej.: Grupo II, camarero/a" },
    { id: "pruebaNoAplica", paso: 2, ambito: "trabajador", tipo: "checkbox", defecto: false, apartado: "h",
      label: "No se pacta periodo de prueba" },
    { id: "pruebaCantidad", paso: 2, ambito: "trabajador", tipo: "number", min: 1, max: 365, incremento: 1, apartado: "h",
      visible: function (d) { return !d.pruebaNoAplica; }, requerido: function (d) { return !d.pruebaNoAplica; },
      label: "Duración del periodo de prueba", ejemplo: "Ej.: 2" },
    { id: "pruebaUnidad", paso: 2, ambito: "trabajador", tipo: "select", defecto: "meses", apartado: "h",
      visible: function (d) { return !d.pruebaNoAplica; },
      opciones: [{ valor: "dias", texto: "días" }, { valor: "semanas", texto: "semanas" }, { valor: "meses", texto: "meses" }],
      label: "Unidad" },
    { id: "tecnicoTitulado", paso: 2, ambito: "trabajador", tipo: "checkbox", defecto: false, apartado: "h",
      visible: function (d) { return !d.pruebaNoAplica && !d.modoHogar; },
      label: "Es un puesto de técnico titulado", ayuda: "Para ellos el periodo de prueba puede llegar a 6 meses." },
    { id: "pruebaCondiciones", paso: 2, ambito: "trabajador", tipo: "textarea", max: 1000, apartado: "h",
      defecto: TEXTOS.pruebaCondiciones, defectoHogar: TEXTOS.hogarPrueba,
      visible: function (d) { return !d.pruebaNoAplica; }, requerido: function (d) { return !d.pruebaNoAplica; },
      label: "Condiciones del periodo de prueba", ayuda: "Texto propuesto a partir de la ley. Puedes adaptarlo." },

    // ---------- Paso 3: Salario (apartado f) ----------
    { id: "salarioBase", paso: 3, ambito: "trabajador", tipo: "number", requerido: true, min: 0.01, max: 999999, incremento: 0.01, sufijo: "€", apartado: "f",
      label: "Salario base (bruto)", ayuda: "Sin contar complementos ni la parte proporcional de las pagas extra.", ejemplo: "Ej.: 1221" },
    { id: "salarioPeriodo", paso: 3, ambito: "trabajador", tipo: "select", requerido: true, defecto: "mes", apartado: "f",
      opciones: [{ valor: "mes", texto: "al mes" }, { valor: "anio", texto: "al año" }, { valor: "hora", texto: "a la hora" }],
      label: "El importe es" },
    { id: "complementos", paso: 3, ambito: "trabajador", tipo: "lista", maxItems: 15, apartado: "f",
      label: "Complementos salariales (opcional)", ayuda: "Cada uno por separado, con su importe bruto mensual: antigüedad, nocturnidad, transporte…",
      subcampos: [
        { id: "nombre", tipo: "text", max: 80, label: "Complemento", ejemplo: "Ej.: Plus de transporte" },
        { id: "importe", tipo: "number", min: 0.01, max: 99999, incremento: 0.01, sufijo: "€/mes", label: "Importe", ejemplo: "Ej.: 60" }
      ] },
    { id: "pagasExtra", paso: 3, ambito: "trabajador", tipo: "number", requerido: true, defecto: 2, min: 0, max: 6, incremento: 1, apartado: "f",
      label: "Pagas extraordinarias al año", ayuda: "El Estatuto de los Trabajadores fija al menos dos; tu convenio puede fijar más." },
    { id: "pagasProrrateadas", paso: 3, ambito: "trabajador", tipo: "checkbox", defecto: false, apartado: "f",
      label: "Las pagas extra se prorratean en cada mensualidad" },
    { id: "periodicidadPago", paso: 3, ambito: "trabajador", tipo: "select", requerido: true, defecto: "mensual", apartado: "f",
      opciones: [{ valor: "mensual", texto: "Mensual" }, { valor: "quincenal", texto: "Quincenal" }, { valor: "semanal", texto: "Semanal" }],
      label: "Periodicidad de pago" },
    { id: "formaPago", paso: 3, ambito: "empresa", tipo: "select", requerido: true, defecto: "transferencia", apartado: "f",
      opciones: [{ valor: "transferencia", texto: "Transferencia bancaria" }, { valor: "cheque", texto: "Cheque" }, { valor: "efectivo", texto: "Efectivo" }],
      label: "Método de pago" },
    { id: "variablesNoAplica", paso: 3, ambito: "trabajador", tipo: "checkbox", defecto: true, apartado: "f",
      label: "No hay retribución variable (comisiones, incentivos, objetivos…)" },
    { id: "hogarEspecie", paso: 3, ambito: "trabajador", tipo: "textarea", max: 600, apartado: "f", visible: function (d) { return !!d.modoHogar; },
      label: "Salario en especie (opcional)",
      ayuda: "Solo si se pacta alojamiento o manutención: qué incluye y qué parte del salario se descuenta, como máximo el 30 % (arts. 5.4 y 8.2 del Real Decreto 1620/2011).",
      ejemplo: "Ej.: Alojamiento y manutención, valorados en el 20 % del salario total." },
    { id: "variables", paso: 3, ambito: "trabajador", tipo: "textarea", max: 1500, apartado: "f",
      visible: function (d) { return !d.variablesNoAplica; }, requerido: function (d) { return !d.variablesNoAplica; },
      label: "Cómo se calcula la parte variable",
      ejemplo: "Ej.: Comisión del 3 % sobre las ventas netas mensuales, que se paga con la nómina del mes siguiente." },

    // ---------- Paso 4: Jornada y vacaciones (apartado g) ----------
    { id: "horasSemanales", paso: 4, ambito: "trabajador", tipo: "number", requerido: true, min: 1, max: 60, incremento: 0.5, apartado: "g",
      label: "Horas de trabajo a la semana", ejemplo: "Ej.: 40" },
    { id: "tipoJornada", paso: 4, ambito: "trabajador", tipo: "select", requerido: true, defecto: "completa", apartado: "g",
      opciones: [{ valor: "completa", texto: "Completa" }, { valor: "parcial", texto: "Parcial" }],
      label: "Tipo de jornada" },
    { id: "horasAnuales", paso: 4, ambito: "trabajador", tipo: "number", visible: noHogar, min: 1, max: 3000, incremento: 1, apartado: "g",
      label: "Horas al año (opcional)", ayuda: "Si tu convenio fija una jornada anual, indícala. Si la dejas en blanco, el documento remite al convenio.", ejemplo: "Ej.: 1792" },
    { id: "horario", paso: 4, ambito: "trabajador", tipo: "textarea", requerido: true, max: 1000, apartado: "g",
      label: "Días y horario", ayuda: "Cómo se reparte la jornada a lo largo del día y de la semana.",
      ejemplo: "Ej.: De martes a sábado, de 10:00 a 14:00 y de 19:00 a 23:00." },
    { id: "nocturnoTurnos", paso: 4, ambito: "trabajador", tipo: "select", requerido: true, defecto: "no", apartado: "g",
      opciones: [{ valor: "no", texto: "No" }, { valor: "nocturno", texto: "Sí, trabajo nocturno" }, { valor: "turnos", texto: "Sí, trabajo a turnos" }, { valor: "ambos", texto: "Sí, nocturno y a turnos" }],
      label: "¿Trabajo nocturno o a turnos?", ayuda: "Trabajo nocturno es el realizado entre las 22:00 y las 6:00 (art. 36 del Estatuto de los Trabajadores)." },
    { id: "nocturnoDetalle", paso: 4, ambito: "trabajador", tipo: "textarea", max: 600, apartado: "g",
      visible: function (d) { return d.nocturnoTurnos && d.nocturnoTurnos !== "no"; }, requerido: function (d) { return d.nocturnoTurnos && d.nocturnoTurnos !== "no"; },
      label: "Detalle del trabajo nocturno o a turnos", ejemplo: "Ej.: Turno rotativo semanal de mañana (7:00–15:00) y tarde (15:00–23:00)." },
    { id: "hogarPresencia", paso: 4, ambito: "trabajador", tipo: "textarea", max: 600, apartado: "g", visible: function (d) { return !!d.modoHogar; },
      label: "Tiempo de presencia (opcional)",
      ayuda: "Horas en las que la persona está a tu disposición sin trabajar: cuántas, cuándo y cómo se pagan o compensan. Si no se compensan con descanso, no pueden superar 20 horas semanales de promedio al mes y se pagan al menos como las ordinarias (arts. 5.4 y 9.2 del Real Decreto 1620/2011).",
      ejemplo: "Ej.: 4 horas semanales, los martes de 17:00 a 21:00, pagadas como horas ordinarias." },
    { id: "hogarPernocta", paso: 4, ambito: "trabajador", tipo: "textarea", max: 400, apartado: "g", visible: function (d) { return !!d.modoHogar; },
      label: "Pernocta en el domicilio (opcional)", ayuda: "Si trabaja como interna o interno, indica cuándo duerme en el domicilio familiar (art. 5.4 del Real Decreto 1620/2011).",
      ejemplo: "Ej.: Empleo interno: pernocta en el domicilio familiar de lunes a viernes." },
    { id: "modificacionJornada", paso: 4, ambito: "empresa", tipo: "textarea", requerido: true, max: 1200, apartado: "g",
      defecto: TEXTOS.modificacionJornada, defectoHogar: TEXTOS.hogarModificacionJornada,
      label: "Cómo se puede cambiar la jornada o los turnos", ayuda: "Texto propuesto con referencia a la ley. Puedes adaptarlo." },
    { id: "horasExtra", paso: 4, ambito: "trabajador", tipo: "textarea", requerido: true, max: 1200, apartado: "g",
      defecto: TEXTOS.horasExtra, defectoHogar: TEXTOS.hogarHorasExtra,
      label: "Horas extraordinarias", ayuda: "Texto propuesto con referencia a la ley. Si la jornada es parcial, el documento usa el texto propio de ese caso." },
    { id: "vacacionesDias", paso: 4, ambito: "trabajador", tipo: "number", requerido: true, defecto: 30, min: 1, max: 60, incremento: 1, apartado: "g",
      label: "Días de vacaciones al año", ayuda: "El mínimo legal son 30 días naturales (art. 38 del Estatuto de los Trabajadores).",
      ayudaHogar: "El mínimo legal son 30 días naturales (art. 9.7 del Real Decreto 1620/2011)." },
    { id: "vacacionesUnidad", paso: 4, ambito: "trabajador", tipo: "select", requerido: true, defecto: "naturales", apartado: "g",
      opciones: [{ valor: "naturales", texto: "naturales" }, { valor: "laborables", texto: "laborables" }],
      label: "Tipo de días" },
    { id: "vacacionesProcedimiento", paso: 4, ambito: "empresa", tipo: "textarea", requerido: true, max: 1000, apartado: "g",
      defecto: TEXTOS.vacacionesProcedimiento, defectoHogar: TEXTOS.hogarVacaciones,
      label: "Cómo se fijan las vacaciones" },
    { id: "irregularNoAplica", paso: 4, ambito: "trabajador", tipo: "checkbox", defecto: true, apartado: "g",
      label: "No hay distribución irregular de la jornada a lo largo del año" },
    { id: "irregularSistema", paso: 4, ambito: "trabajador", tipo: "textarea", max: 1000, apartado: "g",
      visible: function (d) { return !d.irregularNoAplica; }, requerido: function (d) { return !d.irregularNoAplica; },
      label: "Cómo se fija la distribución irregular", ayuda: "Horas y días de referencia en los que la empresa puede pedir que se trabaje.",
      ejemplo: "Ej.: Hasta un 10 % de la jornada anual, en viernes y sábados de junio a septiembre." },
    { id: "irregularPreaviso", paso: 4, ambito: "trabajador", tipo: "text", max: 300, apartado: "g", defecto: TEXTOS.preavisoIrregular,
      visible: function (d) { return !d.irregularNoAplica; }, requerido: function (d) { return !d.irregularNoAplica; },
      label: "Preaviso mínimo antes de empezar o cancelar una tarea" },
    { id: "periodosActividad", paso: 4, ambito: "trabajador", tipo: "textarea", max: 1000, apartado: "g",
      visible: function (d) { return d.tipoContrato === "fijo-discontinuo"; }, requerido: function (d) { return d.tipoContrato === "fijo-discontinuo"; },
      label: "Periodos de actividad e inactividad (o su estimación)",
      ejemplo: "Ej.: De abril a octubre de cada año, según la temporada; el llamamiento se hará por escrito con 15 días de antelación." },

    // ---------- Paso 5: Resto de condiciones (apartados i, j, k, l, m, n, o, p y q) ----------
    { id: "convenioNombre", paso: 5, grupo: "Convenio colectivo", ambito: "empresa", tipo: "text", max: 250, apartado: "o",
      visible: noHogar, requerido: noHogar,
      label: "Nombre del convenio colectivo", ejemplo: "Ej.: Convenio colectivo de hostelería de la Comunidad de Madrid" },
    { id: "convenioCodigo", paso: 5, grupo: "Convenio colectivo", ambito: "empresa", tipo: "text", max: 20, apartado: "o",
      visible: noHogar, requerido: noHogar,
      label: "Código del convenio", ayuda: "Número de 14 cifras que aparece en el boletín oficial o en el buscador de convenios.", ejemplo: "14 cifras, sin espacios" },
    { id: "convenioPublicacion", paso: 5, grupo: "Convenio colectivo", ambito: "empresa", tipo: "text", max: 200, apartado: "o",
      visible: noHogar, requerido: noHogar,
      label: "Boletín y fecha de publicación", ejemplo: "Ej.: BOCM de 15 de marzo de 2025" },
    { id: "convenioVigencia", paso: 5, grupo: "Convenio colectivo", ambito: "empresa", tipo: "text", max: 200, apartado: "o",
      visible: noHogar, requerido: noHogar,
      label: "Periodo de vigencia", ejemplo: "Ej.: Del 1 de enero de 2025 al 31 de diciembre de 2027" },
    { id: "convenioUltraactividad", paso: 5, grupo: "Convenio colectivo", ambito: "empresa", tipo: "text", max: 300, apartado: "o",
      visible: noHogar,
      label: "Ultraactividad (solo si ya terminó su vigencia)", ayuda: "Si el convenio ya venció y sigue aplicándose mientras se negocia otro, indícalo.",
      ejemplo: "Ej.: En ultraactividad desde el 1 de enero de 2026" },
    { id: "formacion", paso: 5, grupo: "Formación y tecnología", ambito: "empresa", tipo: "textarea", requerido: true, max: 1500, apartado: "i",
      defecto: TEXTOS.formacion, defectoHogar: TEXTOS.hogarFormacion,
      label: "Derecho a formación", ayuda: "Texto propuesto con referencia a la ley. Añade la formación que ofrezca tu empresa o tu convenio.",
      ayudaHogar: "Texto propuesto a partir del Real Decreto 893/2024. Puedes adaptarlo." },
    { id: "algoritmos", paso: 5, grupo: "Formación y tecnología", ambito: "empresa", tipo: "select", requerido: true, defecto: "no", apartado: "k",
      visible: noHogar,
      opciones: [{ valor: "no", texto: "No" }, { valor: "si", texto: "Sí" }],
      label: "¿Usa la empresa sistemas automáticos o algoritmos para decidir sobre el trabajo?",
      ayuda: "Por ejemplo, programas que asignan turnos o tareas, fijan sueldos o evalúan el rendimiento de forma automática." },
    { id: "algoritmosDescripcion", paso: 5, grupo: "Formación y tecnología", ambito: "empresa", tipo: "textarea", max: 1500, apartado: "k",
      visible: function (d) { return noHogar(d) && d.algoritmos === "si"; }, requerido: function (d) { return noHogar(d) && d.algoritmos === "si"; },
      label: "Qué deciden y con qué criterios",
      ejemplo: "Ej.: Una aplicación asigna los turnos semanales según la disponibilidad declarada y la previsión de ventas." },
    { id: "planIgualdadEstado", paso: 5, grupo: "Igualdad", ambito: "empresa", tipo: "select", requerido: true, defecto: "no", apartado: "l",
      visible: noHogar,
      opciones: [{ valor: "no", texto: "No dispone" }, { valor: "si", texto: "Sí dispone" }],
      label: "Plan de igualdad", ayuda: "Obligatorio en empresas de 50 o más personas." },
    { id: "planIgualdad", paso: 5, grupo: "Igualdad", ambito: "empresa", tipo: "text", max: 300, apartado: "l",
      visible: function (d) { return noHogar(d) && d.planIgualdadEstado === "si"; }, requerido: function (d) { return noHogar(d) && d.planIgualdadEstado === "si"; },
      label: "Identificación del plan de igualdad", ejemplo: "Ej.: Plan de igualdad 2025-2029, registrado en REGCON el 10/02/2025" },
    { id: "conciliacion", paso: 5, grupo: "Igualdad", ambito: "empresa", tipo: "textarea", max: 1000, apartado: "l",
      visible: noHogar,
      label: "Política de conciliación propia (opcional)", ayuda: "Solo si tu empresa mejora o desarrolla lo que exige la ley. Si no, déjalo en blanco." },
    { id: "protocoloNoDispone", paso: 5, grupo: "Igualdad", ambito: "empresa", tipo: "checkbox", defecto: false, apartado: "l",
      visible: noHogar,
      label: "Todavía no tengo protocolo frente al acoso sexual y por razón de sexo" },
    { id: "protocoloAcoso", paso: 5, grupo: "Igualdad", ambito: "empresa", tipo: "text", max: 300, apartado: "l",
      visible: function (d) { return noHogar(d) && !d.protocoloNoDispone; }, requerido: function (d) { return noHogar(d) && !d.protocoloNoDispone; },
      label: "Dónde se puede consultar el protocolo frente al acoso", ayuda: "Todas las empresas deben tenerlo.",
      ejemplo: "Ej.: Tablón del local y copia entregada junto a este documento" },
    { id: "lgtbiEstado", paso: 5, grupo: "Igualdad", ambito: "empresa", tipo: "select", requerido: true, defecto: "no", apartado: "m",
      visible: noHogar,
      opciones: [{ valor: "no", texto: "No dispone" }, { valor: "si", texto: "Sí dispone" }],
      label: "Medidas para la igualdad de las personas LGTBI", ayuda: "Obligatorias en empresas de más de 50 personas." },
    { id: "lgtbiMedidas", paso: 5, grupo: "Igualdad", ambito: "empresa", tipo: "textarea", max: 1000, apartado: "m",
      visible: function (d) { return noHogar(d) && d.lgtbiEstado === "si"; }, requerido: function (d) { return noHogar(d) && d.lgtbiEstado === "si"; },
      label: "Identificación de las medidas LGTBI", ejemplo: "Ej.: Conjunto de medidas LGTBI acordado el 01/03/2025, disponible en la intranet" },
    { id: "ssMutua", paso: 5, grupo: "Seguridad Social", ambito: "empresa", tipo: "text", max: 300, apartado: "p",
      label: "Mutua colaboradora con la Seguridad Social y qué cubre (opcional)",
      ayuda: "Si no tienes mutua, déjalo en blanco: la cobertura corresponde al INSS.",
      ejemplo: "Ej.: Fremap, para accidentes de trabajo, enfermedades profesionales e incapacidad temporal" },
    { id: "mejoras", paso: 5, grupo: "Seguridad Social", ambito: "empresa", tipo: "textarea", max: 1000, apartado: "p",
      label: "Mejoras voluntarias y planes de pensiones (opcional)",
      ayuda: "Seguros, complementos de la baja o planes de pensiones que pague la empresa, con sus aportaciones. Si no hay, déjalo en blanco." },
    { id: "extincion", paso: 5, grupo: "Fin del contrato y cambios", ambito: "empresa", tipo: "textarea", requerido: true, max: 2000, apartado: "n",
      defecto: TEXTOS.extincion, defectoHogar: TEXTOS.hogarExtincion,
      label: "Fin del contrato y preavisos", ayuda: "Texto propuesto con referencia a la ley. Si tu convenio fija preavisos concretos, añádelos.",
      ayudaHogar: "Texto propuesto a partir del art. 11 del Real Decreto 1620/2011. Puedes adaptarlo." },
    { id: "modificaciones", paso: 5, grupo: "Fin del contrato y cambios", ambito: "empresa", tipo: "textarea", requerido: true, max: 1500, apartado: "q",
      defecto: TEXTOS.modificaciones, defectoHogar: TEXTOS.hogarModificaciones,
      label: "Cuándo y cómo pueden cambiar las condiciones" },
    { id: "ettNoAplica", paso: 5, grupo: "Empresa de trabajo temporal", ambito: "trabajador", tipo: "checkbox", defecto: true, apartado: "j",
      visible: noHogar,
      label: "No aplica: la persona no viene cedida por una empresa de trabajo temporal (ETT)" },
    { id: "ettEmpresaUsuaria", paso: 5, grupo: "Empresa de trabajo temporal", ambito: "trabajador", tipo: "text", max: 200, apartado: "j",
      visible: function (d) { return noHogar(d) && !d.ettNoAplica; }, requerido: function (d) { return noHogar(d) && !d.ettNoAplica; },
      label: "Empresa usuaria", ejemplo: "Ej.: Logística Norte, S.A." },
    { id: "ettCausa", paso: 5, grupo: "Empresa de trabajo temporal", ambito: "trabajador", tipo: "textarea", max: 800, apartado: "j",
      visible: function (d) { return noHogar(d) && !d.ettNoAplica; }, requerido: function (d) { return noHogar(d) && !d.ettNoAplica; },
      label: "Causa del contrato de puesta a disposición" }
  ];

  // Los 17 apartados del art. 3.2 RD 723/2026, en orden. completoTrasPaso: paso tras el que
  // el apartado queda relleno (lo usa la tira a–q de la portada).
  var APARTADOS = [
    { id: "a", titulo: "Identidad de las partes", completoTrasPaso: 2,
      explica: "Quién contrata y a quién: nombre y NIF de la empresa y nombre de la persona trabajadora." },
    { id: "b", titulo: "Fecha de inicio y duración", completoTrasPaso: 2,
      explica: "Cuándo empieza la relación laboral y, si es temporal, cuándo termina o cuánto se prevé que dure." },
    { id: "c", titulo: "Domicilio y centro de trabajo", completoTrasPaso: 1,
      explica: "El domicilio social y, si es distinto, dónde se trabaja: incluido el centro de adscripción en teletrabajo, varios centros o centros móviles." },
    { id: "d", titulo: "Contenido del trabajo y causa de la temporalidad", completoTrasPaso: 2,
      explica: "Qué trabajo se hace y, si el contrato es temporal, su causa legal, los hechos que la justifican y su relación con la duración." },
    { id: "e", titulo: "Grupo o categoría profesional", completoTrasPaso: 2,
      explica: "El grupo o la categoría del puesto, con una descripción que permita saber con precisión en qué consiste." },
    { id: "f", titulo: "Salario", completoTrasPaso: 3,
      explica: "El salario base y cada complemento por separado, cuándo y cómo se pagan, y cómo se calcula la parte variable." },
    { id: "g", titulo: "Tiempo de trabajo y vacaciones", completoTrasPaso: 4,
      explica: "Jornada diaria, semanal y anual y su horario; trabajo nocturno o a turnos; cómo puede cambiar; horas extraordinarias; vacaciones y, si existe, la distribución irregular de la jornada o los periodos de actividad de los fijos discontinuos." },
    { id: "h", titulo: "Periodo de prueba", completoTrasPaso: 2, textoNoAplica: "No se pacta periodo de prueba.",
      explica: "Si se pacta: su duración concreta y la obligación de ambas partes de realizar las experiencias que son su objeto." },
    { id: "i", titulo: "Derecho a formación", completoTrasPaso: 5,
      explica: "La formación a la que se tiene derecho y que proporciona la empresa." },
    { id: "j", titulo: "Empresa de trabajo temporal", completoTrasPaso: 5, textoNoAplica: TEXTOS.ettNo,
      explica: "Solo si la persona viene cedida por una ETT: la empresa usuaria y la causa de cada contrato de puesta a disposición." },
    { id: "k", titulo: "Sistemas algorítmicos o automatizados", completoTrasPaso: 5, textoNoAplica: TEXTOS.algoritmosNo, textoHogar: TEXTOS.hogarAlgoritmos,
      explica: "Si la empresa usa algoritmos o sistemas automáticos para decidir sobre jornada, tareas, salario, promoción, lugar de trabajo o despido, y con qué criterios." },
    { id: "l", titulo: "Plan de igualdad, conciliación y protocolo de acoso", completoTrasPaso: 5, textoHogar: TEXTOS.hogarIgualdad,
      explica: "Si existe plan de igualdad y cuál es; la política de conciliación propia, si la hay; y el protocolo frente al acoso sexual y por razón de sexo." },
    { id: "m", titulo: "Medidas para la igualdad de las personas LGTBI", completoTrasPaso: 5, textoNoAplica: TEXTOS.lgtbiNo, textoHogar: TEXTOS.hogarLgtbi,
      explica: "El conjunto de medidas y recursos para la igualdad real de las personas LGTBI, si la empresa dispone de él." },
    { id: "n", titulo: "Fin del contrato y preavisos", completoTrasPaso: 5,
      explica: "Cómo se extingue el contrato, los requisitos formales y los plazos de preaviso de ambas partes." },
    { id: "o", titulo: "Convenio colectivo", completoTrasPaso: 5, textoHogar: TEXTOS.hogarConvenio,
      explica: "Qué convenio se aplica: su código, boletín y fecha de publicación, vigencia y, si ya venció, su ultraactividad." },
    { id: "p", titulo: "Seguridad Social", completoTrasPaso: 5,
      explica: "La entidad gestora o la mutua con la que colabora la empresa, las mejoras voluntarias y los planes de pensiones con sus aportaciones." },
    { id: "q", titulo: "Posibles cambios en las condiciones", completoTrasPaso: 5,
      explica: "En qué casos pueden cambiar el trabajo, la categoría, el salario o la jornada, y qué procedimiento se sigue." }
  ].map(function (ap) {
    ap.cita = "Art. 3.2." + ap.id + ") del Real Decreto 723/2026";
    return ap;
  });

  // Datos + valores por defecto de los campos que el usuario no ha tocado (undefined).
  // Un campo vaciado a propósito ("") NO se rellena: así la validación puede avisar.
  function withDefaults(datos) {
    datos = datos || {};
    var d = {};
    CAMPOS.forEach(function (c) { if (c.defecto !== undefined) d[c.id] = c.defecto; });
    Object.keys(datos).forEach(function (k) { if (datos[k] !== undefined) d[k] = datos[k]; });
    if (d.modoHogar) {
      CAMPOS.forEach(function (c) { if (c.defectoHogar !== undefined && datos[c.id] === undefined) d[c.id] = c.defectoHogar; });
    }
    return d;
  }

  var CATALOG = { PASOS: PASOS, CAMPOS: CAMPOS, APARTADOS: APARTADOS, TEXTOS: TEXTOS, withDefaults: withDefaults };

  root.__IC_CATALOG__ = CATALOG;
  if (typeof module !== "undefined" && module.exports) module.exports = CATALOG;
})(typeof window !== "undefined" ? window : {});
